services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: alway
    hostname: 'git.your-domain.com'
    env_file:
      - gitlab.env
      - gitlab-omnibus.env       
    ports:
      - '80:80'
      - '443:443'
      - '222:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    logging:
      options:
        max-size: "50M"
        max-file: "3"