tls:
  certificates:
    - certFile: /certs/domaintld.crt
      keyFile: /certs/domaintld.key
  stores:
    default:
      defaultCertificate:
        certFile: /certs/domaintld.crt
        keyFile: /certs/domaintld.key