services:
  freshrss-db:
    image: postgres:18
    restart: ${RESTART_POLICY:-always}
    networks:
      - freshrss-net
    volumes:
      - ./data/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_BASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  freshrss:
    image: freshrss/freshrss:latest
    restart: ${RESTART_POLICY:-always}
    env_file:
      - .env
    networks:
      - freshrss-net
    volumes:
      - ./data/freshrss/data:/var/www/FreshRSS/data
      - ./data/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      FRESHRSS_INSTALL: |-
        --api-enabled
        --base-url ${BASE_URL}
        --db-base ${DB_BASE}
        --db-host ${DB_HOST}
        --db-password ${DB_PASSWORD}
        --db-type pgsql
        --db-user ${DB_USER}
        --default-user admin
        --language ${DEFAULT_LANGUAGE}
      FRESHRSS_USER: |-
        --api-password ${ADMIN_API_PASSWORD}
        --email ${ADMIN_EMAIL}
        --language ${DEFAULT_LANGUAGE}
        --password ${ADMIN_PASSWORD}
        --user admin
    healthcheck:
      test: ["CMD", "cli/health.php"]
      timeout: 10s
      start_period: 60s
      start_interval: 11s
      interval: 75s
      retries: 3

networks:
  freshrss-net: