services:
  freshrss-db:
    image: postgres:18
    restart: ${RESTART_POLICY:-always}
    networks:
      - freshrss-net
    volumes:
      - ./data/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_BASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  freshrss:
    image: freshrss/freshrss:latest
    restart: ${RESTART_POLICY:-always}
    env_file:
      - .env
    networks:
      - freshrss-net
      - ${TRAEFIK_NETWORK}
    volumes:
      - ./data/freshrss/data:/var/www/FreshRSS/data
      - ./data/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      FRESHRSS_INSTALL: |-
        --api-enabled
        --base-url ${BASE_URL}
        --db-base ${DB_BASE}
        --db-host ${DB_HOST}
        --db-password ${DB_PASSWORD}
        --db-type pgsql
        --db-user ${DB_USER}
        --default-user admin
        --language ${DEFAULT_LANGUAGE}
      FRESHRSS_USER: |-
        --api-password ${ADMIN_API_PASSWORD}
        --email ${ADMIN_EMAIL}
        --language ${DEFAULT_LANGUAGE}
        --password ${ADMIN_PASSWORD}
        --user admin
    healthcheck:
      test: ["CMD", "cli/health.php"]
      timeout: 10s
      start_period: 60s
      start_interval: 11s
      interval: 75s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"
      - "traefik.http.routers.freshrss.rule=Host(`${BASE_URL}`)"
      - "traefik.http.routers.freshrss.entrypoints=web"
      - "traefik.http.services.freshrss.loadbalancer.server.port=80"
      - "traefik.http.routers.freshrss.service=freshrss"
      # IF PROXY BEHIND HTTPS
      - "traefik.http.routers.freshrss.middlewares=freshrss-headers"
      - "traefik.http.middlewares.freshrss-headers.headers.sslProxyHeaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.freshrss-headers.headers.sslProxyHeaders.X-Forwarded-For=true"
      - "traefik.http.middlewares.freshrss-headers.headers.sslProxyHeaders.X-Real-Ip=true"
      - "traefik.http.middlewares.freshrss-headers.headers.sslProxyHeaders.X-Forwarded-Port=443"
      - "traefik.http.middlewares.freshrss-headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.freshrss-headers.headers.customRequestHeaders.X-Forwarded-Port=443"
      - "traefik.http.middlewares.freshrss-headers.headers.customRequestHeaders.X-Forwarded-For={remote_ip}"
      - "traefik.http.middlewares.freshrss-headers.headers.customRequestHeaders.X-Real-IP={remote_ip}"

networks:
  freshrss-net:
  ${TRAEFIK_NETWORK}:
    external: true