---
services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
       - ./data/conf.yml:/app/user-data/conf.yml
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
    cpus: 0.5
    mem_limit: 1G
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    #healthcheck:
    #  test: ['CMD', 'node', '/app/services/healthcheck']
    #  interval: 1m30s
    #  timeout: 10s
    # retries: 3
    #  start_period: 40s