services:
  app:
    image: 'jc21/nginx-proxy-manager:${NPM_VERSION:-latest}'
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      # These ports are in format <host-port>:<container-port>
      - '${NPM_HTTP_PORT:-80}:80' # Public HTTP Port
      - '${NPM_HTTPS_PORT:-443}:443' # Public HTTPS Port
      - '${NPM_ADMIN_PORT:-81}:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      # Postgres parameters:
      - DB_POSTGRES_HOST=db
      - DB_POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - DB_POSTGRES_USER=${POSTGRES_USER:-npm}
      - DB_POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-npmpass}
      - DB_POSTGRES_NAME=${POSTGRES_DB:-npm}
      # Uncomment this if IPv6 is not enabled on your host
      # - DISABLE_IPV6=true
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: postgres:17
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-npm}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-npmpass}
      - POSTGRES_DB=${POSTGRES_DB:-npm}
    volumes:
      - ./postgresql:/var/lib/postgresql